export const HORSE_NAMES = [
  'Thunderbolt',
  'Red Fury',
  'Crimson King',
  'Scarlet Flash',
  'Firestorm',
  'Blazing Star',
  'Scarlet Blaze',
  'Cherry Bomb',
  'Ruby Racer',
  'Golden Hoof',
  'Sunfire',
  'Lightning Bolt',
  'Inferno',
  'Flame Rider',
  'Phoenix',
  'Solar Flare',
  'Crimson Rider',
  'Scarlet Knight',
  'Blaze Runner',
  'Red Comet',
]

export const HORSE_COLORS = [
  { hex: '#FF0000', name: 'Red' },
  { hex: '#FF4500', name: 'Orange Red' },
  { hex: '#FFA500', name: 'Orange' },
  { hex: '#FFFF00', name: 'Yellow' },
  { hex: '#FFC0CB', name: 'Pink' },
  { hex: '#FF69B4', name: 'Fuchsia' },
  { hex: '#FF7F50', name: 'Coral' },
  { hex: '#0000FF', name: 'Blue' },
  { hex: '#00008B', name: 'Navy Blue' },
  { hex: '#800080', name: 'Purple' },
  { hex: '#8B4513', name: 'Brown' },
  { hex: '#A52A2A', name: 'Reddish Brown' },
  { hex: '#FFA07A', name: 'Salmon' },
  { hex: '#FFD700', name: 'Gold' },
  { hex: '#ADFF2F', name: 'Light Green' },
  { hex: '#32CD32', name: 'Green' },
  { hex: '#00CED1', name: 'Turquoise' },
  { hex: '#1E90FF', name: 'Dodger Blue' },
  { hex: '#FFB6C1', name: 'Light Pink' },
  { hex: '#FF6347', name: 'Tomato' },
]
